
name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }} 
    strategy: 
      matrix: 
#        operating-system: [macOs-latest]
        operating-system: [ubuntu-latest, ubuntu-16.04]
#        more: [1,2]
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script on ${{ matrix.operating-system }}
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        df -H
#    - name: Mac version
#      run: system_profiler SPSoftwareDataType
#    - name: install npm
#      run: npm install
