
name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }} 
    strategy: 
      matrix: 
        operating-system: [ubuntu-latest, macOs-latest]
        more: [1,2]
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script on ${{ matrix.operating-system }}
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
